# Generated by Django 4.2.6 on 2023-10-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_description_course_section_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='section',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
