# Generated by Django 4.2.6 on 2023-10-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/explanations/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/questions/'),
        ),
    ]
