# Generated by Django 4.2.6 on 2024-02-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_question_explanation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_image',
        ),
    ]
